version: "3.9"
services:

  my-sql:
    image: mysql:8.0
    container_name: unete_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: francix
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: unete_db
    ports:
      - "3306:3306"
    networks:
      - red-unete


networks:
  red-unete:
    driver: bridge
